# Generated by Django 4.2.3 on 2023-07-20 06:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('publication_date', models.DateField()),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
