# Generated by Django 4.2.3 on 2023-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='alt',
            field=models.CharField(default='alt', max_length=200),
            preserve_default=False,
        ),
    ]
