# Generated by Django 4.2.3 on 2023-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(default='helloworld', max_length=200),
            preserve_default=False,
        ),
    ]
