# Generated by Django 4.2.3 on 2023-08-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
    ]
