# Generated by Django 4.2.3 on 2023-10-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.TextField(default='Hello World'),
            preserve_default=False,
        ),
    ]
