# Generated by Django 4.2.3 on 2023-07-25 07:21

import ckeditor.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
