# Generated by Django 4.2.3 on 2023-08-29 07:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
    ]
