# Generated by Django 4.2.3 on 2023-07-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_author_alter_book_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
