# Generated by Django 4.2.3 on 2023-10-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_quote_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
    ]
